import{a as w,S,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const q="51591444-0f19b29ad542d1c79032d94a2",v="https://pixabay.com/api/";async function y(e,t=1,n=15){const o={key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};return(await w.get(v,{params:o})).data}let u;function h(e){const t=e.map(o=>`
    <li class="photo-card">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",t),u?u.refresh():u=new S(".gallery a")}function P(){const e=document.querySelector(".gallery");e.innerHTML=""}function g(){var e;(e=document.querySelector(".loader-wrapper"))==null||e.classList.remove("is-hidden")}function f(){var e;(e=document.querySelector(".loader-wrapper"))==null||e.classList.add("is-hidden")}const M=document.querySelector("#search-form");document.querySelector(".gallery");const p=document.querySelector(".load-more");document.querySelector(".loader-wrapper");let i="",a=1,m=0;const l=15;M.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.currentTarget.elements.query.value.trim(),!!i){a=1,P(),b(),f(),g();try{const t=await y(i,a,l);if(m=t.totalHits,t.hits.length===0){c.info({message:"No images found. Try again."});return}h(t.hits),a*l<m&&L()}catch{c.error({message:"Error fetching data."})}finally{f()}}});p.addEventListener("click",async()=>{a+=1,b(),g();try{const e=await y(i,a,l);h(e.hits);const t=Math.ceil(m/l);a<t?L():c.info({message:"We're sorry, but you've reached the end of search results."}),$()}catch{c.error({message:"Something went wrong while loading more images."})}finally{f()}});function L(){p.classList.remove("is-hidden")}function b(){p.classList.add("is-hidden")}function $(){var t;const{height:e}=((t=document.querySelector(".gallery-item"))==null?void 0:t.getBoundingClientRect())||{height:0};e>0&&window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
