import{a as b,S as w,i as l}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&o(d)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const S="51591444-0f19b29ad542d1c79032d94a2",q="https://pixabay.com/api/";async function y(e,t=1,n=15){const o={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n};return(await b.get(q,{params:o})).data}let u;function p(e){const t=e.map(o=>`
    <li class="photo-card gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o.likes}</p>
        <p><b>Views:</b> ${o.views}</p>
        <p><b>Comments:</b> ${o.comments}</p>
        <p><b>Downloads:</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",t),u?u.refresh():u=new w(".gallery a")}function v(){const e=document.querySelector(".gallery");e.innerHTML=""}function h(){var e;(e=document.querySelector(".loader-wrapper"))==null||e.classList.remove("is-hidden")}function f(){var e;(e=document.querySelector(".loader-wrapper"))==null||e.classList.add("is-hidden")}function g(){var e;(e=document.querySelector(".load-more"))==null||e.classList.remove("is-hidden")}function L(){var e;(e=document.querySelector(".load-more"))==null||e.classList.add("is-hidden")}function P(){const e=document.querySelector(".gallery-item:last-child");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}const M=document.querySelector("#search-form"),$=document.querySelector(".load-more");let i="",a=1,m=0;const c=15;M.addEventListener("submit",async e=>{if(e.preventDefault(),i=e.currentTarget.elements.query.value.trim(),!!i){a=1,v(),L(),f(),h();try{const t=await y(i,a,c);if(m=t.totalHits,t.hits.length===0){l.info({message:"No images found. Try again."});return}p(t.hits),a*c<m&&g()}catch{l.error({message:"Error fetching data."})}finally{f()}}});$.addEventListener("click",async()=>{a+=1,L(),h();try{const e=await y(i,a,c);p(e.hits);const t=Math.ceil(m/c);a<t?g():l.info({message:"We're sorry, but you've reached the end of search results."}),P()}catch{l.error({message:"Something went wrong while loading more images."})}finally{f()}});
//# sourceMappingURL=index.js.map
